import localFont from "next/font/local";
import "./globals.css";
import VerticalNavBar from "./components/navbar";
import {Inter} from 'next/font/google'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        className="font-sans">


        <div className="flex">
          <VerticalNavBar/>
        
            <div className= "flex-1 pl-4 pt-4 bg-slate-800  " >
              {children}
            </div>
        </div>


      </body>
    </html>
  );
}

// import React from 'react';
// import VerticalNavbar from './VerticalNavbar';
// import { Box } from '@mui/material';

// const drawerWidth = 240;

// export default function MainLayout() {
//   return (
//     <Box sx={{ display: 'flex' }}>
//       <VerticalNavbar />
//       <Box
//         component="main"
//         sx={{ flexGrow: 1, bgcolor: 'background.default', p: 3, marginLeft: `${drawerWidth}px` }}
//       >
//         <h1>Welcome to the Dashboard</h1>
//         <p>This is where your main content will go.</p>
//       </Box>
//     </Box>
//   );
// }
