# Generated by Django 5.0 on 2024-09-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JinsTFTAPI', '0002_remove_tactician_placing_tacticianplacements'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_info',
            field=models.JSONField(default=dict),
        ),
    ]
