# Generated by Django 5.0 on 2024-09-29 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JinsTFTAPI', '0003_game_game_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticUnitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.CharField(max_length=100)),
                ('rarity', models.IntegerField(choices=[(0, 1), (1, 2), (2, 3), (4, 4), (6, 5), (9, 0)])),
            ],
        ),
        migrations.CreateModel(
            name='DynamicUnitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemNames', models.JSONField(default=list)),
                ('tier', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JinsTFTAPI.game')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JinsTFTAPI.staticunitdetails')),
            ],
        ),
    ]
