# Generated by Django 5.0 on 2024-10-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JinsTFTAPI', '0004_staticunitdetails_dynamicunitdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicunitdetails',
            name='placement',
            field=models.IntegerField(default=-1),
        ),
    ]
