# Generated by Django 5.0 on 2024-10-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JinsTFTAPI', '0005_dynamicunitdetails_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactician',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tactician',
            name='path',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicunitdetails',
            name='placement',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staticunitdetails',
            name='rarity',
            field=models.IntegerField(),
        ),
    ]
