# Generated by Django 5.0 on 2024-10-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JinsTFTAPI', '0007_statictraitdetails_dynamictraitdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlacements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.IntegerField()),
            ],
        ),
    ]
