# Generated by Django 5.0 on 2024-10-11 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JinsTFTAPI', '0008_gameplacements'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplacements',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='JinsTFTAPI.game'),
            preserve_default=False,
        ),
    ]
